### PR TITLE
Allow passing custom message to potion exceptions

### PR DESCRIPTION
**Pull request by albertodonato**
This uses the exception message (if defined) instead of the status code message for potion exception, allowing to provide custom messages

### CODE REVIEW

**Comment by lyschoening** [comment]
It makes sense to allow for overriding the message. Why not `def __init__(self, message=None)`?

**Comment by albertodonato** [comment]
> It makes sense to allow for overriding the message. Why not `def __init__(self, message=None)`?



> It makes sense to allow for overriding the message. Why not `def __init__(self, message=None)`?

There's no real need to override the Exception constructor, the message is already the first argument there

**Comment by lyschoening** [comment]
Not overriding the constructor is fine. The issue I see with your approach that it seems needlessly inefficient to call `str(self)` and then to check if the resulting string is of zero length. You can do the following and I will merge:
```
if self.args: 
    message = str(self)
else:
    ...
```

**Comment by albertodonato** [comment]
Ok, done it. Thanks

**Comment by albertodonato** [comment]
Thanks for merging! Is there any plan to make a new stable release?

**Pull request merged**
