### PR TITLE
peewee backend

### PR DESCRIPTION
**Pull request by kolanos**
Trying my hand at a peewee backend for potion. The only part I haven't figured out is the relation_add and relation_remove methods. Peewee supports many-to-many relations using a playhouse extension, which is currently implemented. But for one-to-many, for example, the relation_* methods appear to be implemented in a reverse manner to what peewee expects. For example:

    class User(Model):
        parent = ForeignKeyField('self', null=True, related_name='children')
        name = CharField()

You can't do:

    parent = User.create(name='foo')
    child = User.create(name='bar')
    parent.children.add(child)

Instead you would do:

    child.parent = parent

But relation_add/relation_remove only provide the item attribute and not the target attribute. So I'd have to figure out a way to get that attribute via peewee in some way. Haven't found a way to do this yet.

### CODE REVIEW

**Comment by kolanos** [comment]
Ok, I've updated the backend to support these reverse relationships.

**Comment by lyschoening** [comment]
Thank you for all your work! This will be a great addition to Potion. Your implementation looks very neat. We should merge it as soon as that failing test is fixed. 

`relation_add()` and `relation_remove()` were a bit tricky to implement in SQLAlchemy as well. Ironically, I've ended up with the current approach because SQLAlchemy doesn't have a good way to look up the reverse side of a relation.

I will make some time this weekend  to try out your backend, document, and publish it. (Good opportunity for me to check out peewee. It seems to have gone a long way since I last looked at it.) The unit tests need some refactoring so that both backends have test cases for filters and signals, and not just SQLAlchemy.

Peewee should not be a mandatory requirement, but neither should SQLAlchemy, so I would probably switch to making them both optional. This can be done after we merge.

**Comment by kolanos** [comment]
I'm not sure why that test is failing, it doesn't fail when I run `python setup.py test` locally. I can look into it further, but if you want to merge and see if you can figure it out feel free. I agree with your thoughts about the sqlalchemy and peewee dependencies being optional.

**Comment by lyschoening** [comment]
It’s only in Python 3. I can look into it.

https://travis-ci.org/biosustain/potion/jobs/79407045#L549 <https://travis-ci.org/biosustain/potion/jobs/79407045#L549>

**Comment by kolanos** [comment]
Fixed the test, but there should be a better way to determine a unique constraint has failed.

**Comment by lyschoening** [comment]
I will document this a bit further and then release this in the next few days. 

I've added a feature in master that might be useful for you. `Api` now takes a `default_manager` argument where you can define the `PeeweeManager` once and automatically use it with all resources inheriting `ModelResource`. Alternatively, you can of course make your own "PeeweeResource" and use that:

```
class PeeweeResource(ModelResource):
    class Meta:
        manager = PeeweeManager
```

Flask-SQLAlchemy is no longer a required dependency.

**Comment by kolanos** [comment]
The default manager feature is a good one, it occurred to me as well when I noticed that the SQLAlchemy manager was hardcoded in the ModelResource class. But I didn't want to let the scope of this pull request go beyond the backend itself.

**Comment by kolanos** [comment]
When is the next release planned? Any additional features planned for 0.7.5?

Also, to expand on making SQLAlchemy and Peewee optional dependencies, what do you think about making the backends `contribs` like the `principal` contrib? Also, I would very much be interested in making that principal implementation more abstract so that it can use a peewee backend. Maybe a Manager mixin class?

**Comment by lyschoening** [comment]
Sorry, I’ve been lagging a bit. Pre-vacation busyness & now travelling. I am still planning to document the peewee backend as soon as I get the time and then to release it. However, I can simply release the new version as it is now if you like. 

I do have some longer term plans for built-in caching solution for `ModelResource`. I was also hoping to bundle a WebSocket subscription interface for which I currently use a Redis connection and a separate SocketIO server, but Flask isn’t designed for async so I have not yet figured out a good way to do this.

It should be possible to port the principals extension. Most of the backend-specific logic is in `HybridRelationshipNeed.make_expression()`. This function could be refactored to take the backend instance as a parameter. Each backend would then need a method for building the expression in order to support principals permissions.

This would muddy the meaning of the ‘contrib’ package. The backends and ModelResource could go into that package, but they are such a big part of the code base that I don’t think it makes sense.

**Comment by kolanos** [comment]
No worries, I was out-of-town for most of this week as well. I suppose I could take a crack at the peewee docs. Was also looking at putting together an oauth contrib that may also integrate with principal permissions.

**Pull request merged**
